"""add reading and reading_card models

Revision ID: 2b64ef30552e
Revises: 91a18dc1b81d
Create Date: 2025-10-19 22:24:38.733458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b64ef30552e'
down_revision: Union[str, None] = '91a18dc1b81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='사용자 ID (User 모델 생성 후 ForeignKey 추가 예정)'),
    sa.Column('spread_type', sa.String(length=50), nullable=False, comment='스프레드 타입 (one_card, three_card_past_present_future, etc.)'),
    sa.Column('question', sa.Text(), nullable=False, comment='사용자의 질문'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='리딩 카테고리 (love, career, finance, health, etc.)'),
    sa.Column('card_relationships', sa.Text(), nullable=True, comment='카드 간 관계 설명 (쓰리카드 이상에서 사용)'),
    sa.Column('overall_reading', sa.Text(), nullable=False, comment='AI가 생성한 종합 리딩'),
    sa.Column('advice', sa.JSON(), nullable=False, comment='조언 객체 (immediate_action, short_term, long_term, mindset, cautions)'),
    sa.Column('summary', sa.String(length=200), nullable=False, comment='한 줄 요약 메시지'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_readings_created_at', 'readings', ['created_at'], unique=False)
    op.create_index('idx_readings_spread_type', 'readings', ['spread_type'], unique=False)
    op.create_index('idx_readings_user_created', 'readings', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_readings_category'), 'readings', ['category'], unique=False)
    op.create_index(op.f('ix_readings_created_at'), 'readings', ['created_at'], unique=False)
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_index(op.f('ix_readings_spread_type'), 'readings', ['spread_type'], unique=False)
    op.create_index(op.f('ix_readings_user_id'), 'readings', ['user_id'], unique=False)
    op.create_table('reading_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=False, comment='Reading ID'),
    sa.Column('card_id', sa.Integer(), nullable=False, comment='Card ID'),
    sa.Column('position', sa.String(length=50), nullable=False, comment='카드 위치 (past, present, future, single, situation, action, outcome, etc.)'),
    sa.Column('orientation', sa.String(length=20), nullable=False, comment='카드 방향 (upright, reversed)'),
    sa.Column('interpretation', sa.Text(), nullable=False, comment='AI가 생성한 카드 해석'),
    sa.Column('key_message', sa.String(length=100), nullable=False, comment='핵심 메시지 한 줄'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reading_cards_card', 'reading_cards', ['card_id'], unique=False)
    op.create_index('idx_reading_cards_reading', 'reading_cards', ['reading_id'], unique=False)
    op.create_index('idx_reading_cards_reading_position', 'reading_cards', ['reading_id', 'position'], unique=False)
    op.create_index(op.f('ix_reading_cards_card_id'), 'reading_cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_reading_cards_id'), 'reading_cards', ['id'], unique=False)
    op.create_index(op.f('ix_reading_cards_reading_id'), 'reading_cards', ['reading_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_cards_reading_id'), table_name='reading_cards')
    op.drop_index(op.f('ix_reading_cards_id'), table_name='reading_cards')
    op.drop_index(op.f('ix_reading_cards_card_id'), table_name='reading_cards')
    op.drop_index('idx_reading_cards_reading_position', table_name='reading_cards')
    op.drop_index('idx_reading_cards_reading', table_name='reading_cards')
    op.drop_index('idx_reading_cards_card', table_name='reading_cards')
    op.drop_table('reading_cards')
    op.drop_index(op.f('ix_readings_user_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_spread_type'), table_name='readings')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_created_at'), table_name='readings')
    op.drop_index(op.f('ix_readings_category'), table_name='readings')
    op.drop_index('idx_readings_user_created', table_name='readings')
    op.drop_index('idx_readings_spread_type', table_name='readings')
    op.drop_index('idx_readings_created_at', table_name='readings')
    op.drop_table('readings')
    # ### end Alembic commands ###
