"""add feedback model

Revision ID: 872c9c01b184
Revises: b8315e000034
Create Date: 2025-10-20 22:10:14.057355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872c9c01b184'
down_revision: Union[str, None] = 'b8315e000034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False, comment='피드백 고유 식별자'),
    sa.Column('reading_id', sa.UUID(), nullable=False, comment='연관된 리딩 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='피드백 작성자 ID'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='별점 평가 (1-5)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='사용자 코멘트 (선택사항)'),
    sa.Column('helpful', sa.Boolean(), nullable=False, comment='리딩이 유용했는지 여부'),
    sa.Column('accurate', sa.Boolean(), nullable=False, comment='리딩이 정확했는지 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='피드백 생성 시각'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='피드백 수정 시각'),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reading_id', 'user_id', name='uq_feedback_reading_user'),
    comment='타로 리딩 피드백 테이블'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
