"""Create cards table

Revision ID: 91a18dc1b81d
Revises: 
Create Date: 2025-10-18 23:50:10.923621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a18dc1b81d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ko', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('arcana_type', sa.Enum('MAJOR', 'MINOR', name='arcanatype'), nullable=False),
    sa.Column('suit', sa.Enum('WANDS', 'CUPS', 'SWORDS', 'PENTACLES', name='suit'), nullable=True),
    sa.Column('keywords_upright', sa.JSON(), nullable=False),
    sa.Column('keywords_reversed', sa.JSON(), nullable=False),
    sa.Column('meaning_upright', sa.Text(), nullable=False),
    sa.Column('meaning_reversed', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symbolism', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arcana_suit', 'cards', ['arcana_type', 'suit'], unique=False)
    op.create_index('idx_name_search', 'cards', ['name', 'name_ko'], unique=False)
    op.create_index(op.f('ix_cards_arcana_type'), 'cards', ['arcana_type'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_arcana_type'), table_name='cards')
    op.drop_index('idx_name_search', table_name='cards')
    op.drop_index('idx_arcana_suit', table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
