"""add user model and update reading relationship

Revision ID: b8315e000034
Revises: 2b64ef30552e
Create Date: 2025-10-20 13:13:14.563477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8315e000034'
down_revision: Union[str, None] = '2b64ef30552e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='사용자 고유 ID (UUID)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 주소'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='표시 이름'),
    sa.Column('photo_url', sa.String(length=500), nullable=True, comment='프로필 사진 URL'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('provider_id', sa.String(length=50), nullable=False, comment='인증 Provider 식별자 (firebase, auth0, custom_jwt 등)'),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='Provider의 사용자 ID (firebase_abc123, auth0_xyz789 등)'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='이메일 인증 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='계정 활성화 여부'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='관리자 여부'),
    sa.Column('user_metadata', sa.JSON(), nullable=True, comment='추가 사용자 메타데이터 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='계정 생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 업데이트 시간'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_provider', 'users', ['provider_id', 'provider_user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=True)
    op.alter_column('readings', 'user_id',
               existing_type=sa.UUID(),
               comment='사용자 ID',
               existing_comment='사용자 ID (User 모델 생성 후 ForeignKey 추가 예정)',
               existing_nullable=True)
    op.create_foreign_key(None, 'readings', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readings', type_='foreignkey')
    op.alter_column('readings', 'user_id',
               existing_type=sa.UUID(),
               comment='사용자 ID (User 모델 생성 후 ForeignKey 추가 예정)',
               existing_comment='사용자 ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_provider', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
